version: '3'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    environment:
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: poc
      POSTGRES_DB: poc
    deploy:
      resources:
        limits:
          cpus: "${CPU_LIMITS}"
          memory: "${MEMORY_LIMITS}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - "${VOLUME_PATH}/timescaledb:/var/lib/postgresql/data"

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: poc
      CLICKHOUSE_PASSWORD: poc
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    deploy:
      resources:
        limits:
          cpus: "${CPU_LIMITS}"
          memory: "${MEMORY_LIMITS}"
    ports:
      - "${CLICK_HTTP_PORT}:8123"
      - "${CLICK_TCP_PORT}:9000"
    volumes:
      - "${VOLUME_PATH}/clickhouse:/var/lib/clickhouse"

  data_init:
    build:
      context: ./insert_data
      dockerfile: Dockerfile
    container_name: initial_data
    depends_on:
      - timescaledb
      - clickhouse
    volumes:
      - "${VOLUME_PATH}/test_data:/data/test_data"

volumes:
  timescaledb_data: 
  clickhouse_data:
